default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost

development:
   adapter: postgresql
   encoding: unicode
   database: wipers_development
   username: rubyuser
   password: <%= Rails.application.credentials.database_key[:development] %>

test:
   adapter: postgresql
   encoding: unicode
   database: wipers_test
   username: rubyuser
   password: <%= Rails.application.credentials.database_key[:test] %>
 
production:
   adapter: postgresql
   encoding: unicode
   database: wipers_production
   username: deploy
   password: <%= Rails.application.credentials.database_key[:production] %>
