# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
   adapter: postgresql
   encoding: unicode
   database: wipers_development
   username: rubyuser
   password: CkeyCaldHALf

test:
   adapter: postgresql
   encoding: unicode
   database: wipers_test
   username: rubyuser
   password: CkeyCaldHALf
 
production:
   adapter: postgresql
   encoding: unicode
   database: wipers_production
   username: deploy
   password: 2Wd/[]sV@v6k)4_2"f.{@x`Z
